### ISSUE TITLE
Bower package is out-of-date

### ISSUE THREAD

**Issue by gerrod** [twilson63/ngUpload#124]
Hi there - I'm getting an error with ng-Upload which I know is fixed in the latest version here on github, but that's not what I'm getting via bower.

Speficially, the `try/catch` around accessing the `contentDocument` from the iframe after upload complete is needed to fix an `Access is denied` error that you get from Internet Explorer if the upload fails:

    var bodyContent = (iframe[0].contentDocument ||
        iframe[0].contentWindow.document).body;

Could you please update your bower package to include this feature? I'd like to take advantage of the `errorCatcher` to handle this!

Thanks!

**Comment by twilson63** [comment]
Hey @gerrod, 

I just double checked and I was able to pull down 0.5.13 from bower with no problems, did you check your bower.json?  What is the version of ngUpload?

Thanks

Tom

**Comment by twilson63** [comment]
nvm, I found the issue and bumped to 0.5.14 - you should be good to go!

Thanks

Tom

**Comment by gerrod** [comment]
Awesome, thanks Tom!

On Tue, Jan 20, 2015 at 7:19 AM, Tom Wilson <notifications@github.com>
wrote:

> nvm, I found the issue and bumped to 0.5.14 - you should be good to go!
>
> Thanks
>
> Tom
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twilson63/ngUpload/issues/124#issuecomment-70562672>.
>



-- 
*Gerrod Thomas*
*m: +61 466 55 00 20*
*e: gerrod@gerrod.com <gerrod@gerrod.com>*
