### ISSUE TITLE
Processing a full form using ngUpload oin IE populate JSON return as a new tab json or save/open x.json file

### ISSUE THREAD

**Issue by msalahz** [twilson63/ngUpload#23]
If you submit form in Example 5 - Processing a full form on IE the return will be viewed in a new tab as JSON as you can see in screenshot
![Untitled](https://f.cloud.github.com/assets/3384518/325562/c0f58234-9b0e-11e2-894d-7ed44cfc8396.jpg)

**Comment by cidevant** [comment]
Be aware of response status codes! IE __ignores response body data__ if response code is 500. So you cant pass any additional data. I globally changed all 500 to 422 for all upload actions - this solved my problem.
