### ISSUE TITLE
Response JSON is surrounded with HTML...?

### ISSUE THREAD

**Issue by Siyfion** [twilson63/ngUpload#46]
I am using ngUpload to sent an image to the server, after which the server sends back a JSON object containing the image's ID and filename. The issue is the response I get is like this:

```
"<pre style="word-wrap: break-word; white-space: pre-wrap;">[
  {
    "_id": "51c2bac6b9c53fa200d4b9eb",
    "filename": "Blue4_Large.svg"
  }
]</pre>"
```

Which obviously cannot be run thought `JSON.parse()` without issues.

I **did** have this working, so I think a recent update to ngUpload may have broken this for me. Any idea why this is occurring? If so, is there an easy way I can fix this?

**Comment by mrsalesi** [comment]
In ajaxFileUpload.js in uploadCallback() replace 
io.contentWindow.document.body.innerHTML.innerHTML

with

$(io.contentWindow.document.body.innerHTML).html()

[https://stackoverflow.com/a/36675841/3600935](https://stackoverflow.com/a/36675841/3600935)
